name: "Docker Socket Proxy"
description: "Proxy over your Docker socket to a port"
version: "1.0.1"
slug: "ha-docker-socket-proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  2375/tcp: 2375
ports_description:
  2375/tcp: Proxy port for Docker API
docker_api: true
full_access: true
url: https://github.com/rikardronnkvist/ha-docker-socket-proxy
