name: "Docker Socket Proxy"
description: "Moved to other repo!"
version: "2.0.0"
slug: "ha-docker-socket-proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
docker_api: true
full_access: true
url: https://github.com/rikardronnkvist/ha-docker-socket-proxy
